### ISSUE TITLE
ember install ember-gsap error 

### ISSUE THREAD

**Issue by marialomidze** [willviles/ember-gsap#10]
ember install ember-gsap fails with npm install --save-dev --loglevel error ember-gsap
npm ERR! tar.unpack untar error ...\npm-cache\ember-gsap\0.3.2\package.tgz

**Comment by willviles** [comment]
@marialomidze, are you using a Windows OS by any chance? Could be related to https://github.com/willviles/ember-useragent/issues/7.

**Comment by BryanCrotaz** [comment]
We have the same issue on Windows OS. Agree it looks like the ember-useragent error

**Comment by willviles** [comment]
@BryanCrotaz I notice you've forked the repo. Have you got a PR to submit? Or shall I issue a fix?

**Comment by BryanCrotaz** [comment]
Was going to fix it then realised I didn't know how.

Bryan Crotaz
Silver Curve

On 9 Sep 2017, at 15:42, Will Viles <notifications@github.com> wrote:

@BryanCrotaz <https://github.com/bryancrotaz> I notice you've forked the
repo. Have you got a PR to submit? Or shall I issue a fix?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/willviles/ember-gsap/issues/10#issuecomment-328281419>,
or mute the thread

**Comment by willviles** [comment]
@marialomidze @BryanCrotaz, I've updated .npmignore and published `0.3.3`. Please let me know if this fixes the problem!

**Comment by marialomidze** [comment]
It works for me now. Thanks!
